#!/bin/bash
cd ~/Documents/Piscine42/$1
if [ "$3" = "true" ]
then
    echo "No commit in sub-repo"
else
    git add *
    git commit -m "$2"
fi
mv .git/ .git_unloaded/
cd ..
git add -f $1/
git commit -m "$1/$2"
cd $1
mv .git_unloaded/ .git/
cd ..
